development:
  adapter: postgresql
  encoding: utf8
  database: scott_development
  pool: 5
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: scott_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: scott_production
  pool: 5
  password: